[package]
name = "rulemin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rulelib = { path = "../rulelib" }
rustyline = { version = ">= 13.0.0" }
term-table = { version = "1.3.2" }